// @ts-check
import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import jsxA11y from 'eslint-plugin-jsx-a11y';

export default tseslint.config(
  // src/api/schema.d.ts is generated by `npm run generate:api` and is not authored here, so it
  // is ignored for the same reason dist/ is. It trips consistent-indexed-object-style, and the
  // right answer to generated output failing a style rule is not to relax the rule.
  { ignores: ['dist/', 'coverage/', 'playwright-report/', 'src/api/schema.d.ts'] },
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      eslint.configs.recommended,
      ...tseslint.configs.strictTypeChecked,
      ...tseslint.configs.stylisticTypeChecked,
    ],
    languageOptions: {
      parserOptions: { projectService: true },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
      'jsx-a11y': jsxA11y,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.configs.recommended.rules,
      'react-refresh/only-export-components': ['error', { allowConstantExport: true }],

      // Type safety
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-non-null-assertion': 'error',
      '@typescript-eslint/explicit-function-return-type': ['error', { allowExpressions: true }],
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',

      // Never silently swallow a failure - see frontend/CLAUDE.md
      'no-empty': ['error', { allowEmptyCatch: false }],
    },
  },
  {
    // e2e/ is Playwright test code, never React component code. Its fixtures take a `use`
    // callback parameter - the same name as the React hook - which eslint-plugin-react-hooks
    // otherwise flags as a hook called outside a component. The rule's intent (hooks only run
    // inside components/hooks) does not apply to a Playwright fixture function.
    files: ['e2e/**/*.ts'],
    rules: {
      'react-hooks/rules-of-hooks': 'off',
    },
  },
);
