/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/orders": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Lists orders newest first, one page at a time. */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    readonly limit?: number | string;
                    readonly cursor?: string;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["OrderPageResponse"];
                        readonly "application/json": components["schemas"]["OrderPageResponse"];
                        readonly "text/json": components["schemas"]["OrderPageResponse"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        /** Places an order and returns its new identifier. */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["PlaceOrderRequest"];
                    readonly "text/json": components["schemas"]["PlaceOrderRequest"];
                    readonly "application/*+json": components["schemas"]["PlaceOrderRequest"];
                };
            };
            readonly responses: {
                /** @description Created */
                readonly 201: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": string;
                        readonly "application/json": string;
                        readonly "text/json": string;
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/orders/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Fetches a single order by its identifier. */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["OrderResponse"];
                        readonly "application/json": components["schemas"]["OrderResponse"];
                        readonly "text/json": components["schemas"]["OrderResponse"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        readonly OrderListItemResponse: {
            /** Format: uuid */
            readonly id: string;
            readonly sku: string;
            /** Format: int32 */
            readonly quantity: number | string;
            /** Format: date-time */
            readonly placedAt: string;
        };
        readonly OrderPageResponse: {
            readonly items: readonly components["schemas"]["OrderListItemResponse"][];
            readonly nextCursor: null | string;
        };
        readonly OrderResponse: {
            /** Format: uuid */
            readonly id: string;
            readonly sku: string;
            /** Format: int32 */
            readonly quantity: number | string;
            /** Format: date-time */
            readonly placedAt: string;
        };
        /**
         * @description Business-rule validation (non-empty, max length, positive quantity) is owned by
         *     `PlaceOrderValidator` in the validation behavior — not duplicated here as
         *     DataAnnotations. See `src/Api/CLAUDE.md`.
         */
        readonly PlaceOrderRequest: {
            readonly sku: string;
            /** Format: int32 */
            readonly quantity: number | string;
        };
        readonly ProblemDetails: {
            readonly type?: null | string;
            readonly title?: null | string;
            /** Format: int32 */
            readonly status?: null | number | string;
            readonly detail?: null | string;
            readonly instance?: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
