/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/rates": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * The current rate to convert one unit of from into
         *     to. 503 is this endpoint's distinctive failure: the provider's own
         *     retry budget (ADR 0014) has already been exhausted by the time one reaches a caller here.
         */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    readonly from?: string;
                    readonly to?: string;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ExchangeRateResponse"];
                        readonly "application/json": components["schemas"]["ExchangeRateResponse"];
                        readonly "text/json": components["schemas"]["ExchangeRateResponse"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Service Unavailable */
                readonly 503: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/products": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Lists the catalogue newest first, one page at a time. */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    readonly limit?: number | string;
                    readonly cursor?: string;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProductPageResponse"];
                        readonly "application/json": components["schemas"]["ProductPageResponse"];
                        readonly "text/json": components["schemas"]["ProductPageResponse"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        /** Adds a product to the catalogue and returns its new identifier. */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["CreateProductRequest"];
                    readonly "text/json": components["schemas"]["CreateProductRequest"];
                    readonly "application/*+json": components["schemas"]["CreateProductRequest"];
                };
            };
            readonly responses: {
                /** @description Created */
                readonly 201: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": string;
                        readonly "application/json": string;
                        readonly "text/json": string;
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/products/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Fetches a single product by its identifier. */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProductResponse"];
                        readonly "application/json": components["schemas"]["ProductResponse"];
                        readonly "text/json": components["schemas"]["ProductResponse"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        /** Replaces a product's editable fields. The sku is not among them. */
        readonly put: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["UpdateProductRequest"];
                    readonly "text/json": components["schemas"]["UpdateProductRequest"];
                    readonly "application/*+json": components["schemas"]["UpdateProductRequest"];
                };
            };
            readonly responses: {
                /** @description No Content */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/orders": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Lists orders newest first, one page at a time. */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    readonly limit?: number | string;
                    readonly cursor?: string;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["OrderPageResponse"];
                        readonly "application/json": components["schemas"]["OrderPageResponse"];
                        readonly "text/json": components["schemas"]["OrderPageResponse"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        /** Places an order and returns its new identifier. */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["PlaceOrderRequest"];
                    readonly "text/json": components["schemas"]["PlaceOrderRequest"];
                    readonly "application/*+json": components["schemas"]["PlaceOrderRequest"];
                };
            };
            readonly responses: {
                /** @description Created */
                readonly 201: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": string;
                        readonly "application/json": string;
                        readonly "text/json": string;
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/orders/{id}/ship": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Marks one of the caller's own orders as shipped. 409 if it has already shipped or was
         *     cancelled — an illegal transition is a conflict with existing state, not a malformed
         *     request.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["OrderStatusResponse"];
                        readonly "application/json": components["schemas"]["OrderStatusResponse"];
                        readonly "text/json": components["schemas"]["OrderStatusResponse"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/orders/{id}/cancel": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Cancels one of the caller's own orders. 409 if it has already shipped or was already
         *     cancelled.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["CancelOrderRequest"];
                    readonly "text/json": components["schemas"]["CancelOrderRequest"];
                    readonly "application/*+json": components["schemas"]["CancelOrderRequest"];
                };
            };
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["OrderStatusResponse"];
                        readonly "application/json": components["schemas"]["OrderStatusResponse"];
                        readonly "text/json": components["schemas"]["OrderStatusResponse"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/orders/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Fetches a single order by its identifier. */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["OrderResponse"];
                        readonly "application/json": components["schemas"]["OrderResponse"];
                        readonly "text/json": components["schemas"]["OrderResponse"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/notifications": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Lists the caller's notifications, newest first, one page at a time. */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    readonly limit?: number | string;
                    readonly cursor?: string;
                    readonly unreadOnly?: boolean;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["NotificationPageResponse"];
                        readonly "application/json": components["schemas"]["NotificationPageResponse"];
                        readonly "text/json": components["schemas"]["NotificationPageResponse"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/notifications/unread-count": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** The caller's unread count, for a badge. */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["UnreadCountResponse"];
                        readonly "application/json": components["schemas"]["UnreadCountResponse"];
                        readonly "text/json": components["schemas"]["UnreadCountResponse"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/notifications/{id}/read": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Marks one notification read. Idempotent — marking an already-read one answers 200 with a
         *     MarkedCount of zero, not an error.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["NotificationReadResponse"];
                        readonly "application/json": components["schemas"]["NotificationReadResponse"];
                        readonly "text/json": components["schemas"]["NotificationReadResponse"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/notifications/read-all": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Marks every unread notification read. */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["NotificationReadResponse"];
                        readonly "application/json": components["schemas"]["NotificationReadResponse"];
                        readonly "text/json": components["schemas"]["NotificationReadResponse"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/register": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Creates an account and signs it in. */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["RegisterRequest"];
                    readonly "text/json": components["schemas"]["RegisterRequest"];
                    readonly "application/*+json": components["schemas"]["RegisterRequest"];
                };
            };
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["SessionResponse"];
                        readonly "application/json": components["schemas"]["SessionResponse"];
                        readonly "text/json": components["schemas"]["SessionResponse"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Too Many Requests */
                readonly 429: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/login": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Signs in with a username and password. */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["LoginRequest"];
                    readonly "text/json": components["schemas"]["LoginRequest"];
                    readonly "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["SessionResponse"];
                        readonly "application/json": components["schemas"]["SessionResponse"];
                        readonly "text/json": components["schemas"]["SessionResponse"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Too Many Requests */
                readonly 429: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/logout": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Signs out, clearing the session cookie.
         * @description Anonymous deliberately: signing out when the cookie has already expired is the caller
         *     getting what they asked for, not an error worth a 401.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description No Content */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/me": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Returns the signed-in user. */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["SessionResponse"];
                        readonly "application/json": components["schemas"]["SessionResponse"];
                        readonly "text/json": components["schemas"]["SessionResponse"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/change-password": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Changes the signed-in user's own password. */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["ChangePasswordRequest"];
                    readonly "text/json": components["schemas"]["ChangePasswordRequest"];
                    readonly "application/*+json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            readonly responses: {
                /** @description No Content */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/sign-out-everywhere": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Invalidates every session for the signed-in user, including this one. */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description No Content */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ProblemDetails"];
                        readonly "application/json": components["schemas"]["ProblemDetails"];
                        readonly "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The reason is owned by `CancelOrderValidator`, not duplicated here as a DataAnnotation —
         *     see the note on PlaceOrderRequest.
         */
        readonly CancelOrderRequest: {
            readonly reason: string;
        };
        readonly ChangePasswordRequest: {
            readonly currentPassword: string;
            readonly newPassword: string;
        };
        /**
         * @description Business-rule validation (non-empty, max length, price range and scale) is owned by
         *     `CreateProductValidator` in the validation behavior — not duplicated here as
         *     DataAnnotations. See `src/Api/CLAUDE.md`.
         */
        readonly CreateProductRequest: {
            readonly sku: string;
            readonly name: string;
            readonly description?: null | string;
            /** Format: double */
            readonly price: number | string;
        };
        readonly ExchangeRateResponse: {
            readonly from: string;
            readonly to: string;
            /** Format: double */
            readonly rate: number | string;
            /** Format: date */
            readonly asOf: string;
        };
        readonly LoginRequest: {
            readonly username: string;
            readonly password: string;
            /**
             * @description Whether the session cookie outlives the browser session. Maps to the auth cookie's
             *     IsPersistent, which is the whole of what "remember me" means under cookie authentication.
             */
            readonly rememberMe: boolean;
        };
        /**
         * @description What a notification is about. Persisted by name rather than by number (see the EF
         *     configuration), so the numeric values here are free to be reordered — but the NAMES are a
         *     stored contract: renaming one orphans every row already written under the old name.
         * @enum {unknown}
         */
        readonly NotificationKind: "OrderPlaced" | "OrderShipped" | "OrderCancelled" | "ProductPriceChanged";
        readonly NotificationPageResponse: {
            readonly items: readonly components["schemas"]["NotificationResponse"][];
            readonly nextCursor: null | string;
        };
        /** @description What both mark-read endpoints answer with. */
        readonly NotificationReadResponse: {
            /**
             * Format: int32
             * @description How many this call actually changed. Zero is a success: re-reading something already read
             *     is idempotent, not an error.
             */
            readonly markedCount: number | string;
            /**
             * Format: int32
             * @description The badge count after the change, so the client needs no second round-trip.
             */
            readonly unreadCount: number | string;
        };
        readonly NotificationResponse: {
            /** Format: uuid */
            readonly id: string;
            /**
             * @description Serialized as its NAME, not its number — `Program.cs` configures a
             *     `JsonStringEnumConverter`, and the generated OpenAPI document and
             *     `frontend/src/api/schema.d.ts` both carry it as a string union. A client switching on
             *     this gets a compile error when a kind is added, rather than an unhandled integer.
             */
            readonly kind: components["schemas"]["NotificationKind"];
            readonly title: string;
            readonly body: string;
            /**
             * Format: uuid
             * @description The order or product this is about, for deep-linking. Null when the subject is gone or was
             *     never recorded — see `Notification.SubjectId`.
             */
            readonly subjectId?: null | string;
            /** Format: date-time */
            readonly createdAt: string;
            /**
             * Format: date-time
             * @description Null while unread. The single source of read-ness; there is no separate flag.
             */
            readonly readAt?: null | string;
        };
        readonly OrderListItemResponse: {
            /** Format: uuid */
            readonly id: string;
            readonly sku: string;
            /** Format: int32 */
            readonly quantity: number | string;
            /** Format: date-time */
            readonly placedAt: string;
            /**
             * Format: uuid
             * @description The catalogue product as it was when the order was placed. Null on orders that predate the
             *     catalogue link — those render as the bare sku with no price.
             */
            readonly productId?: null | string;
            readonly productName?: null | string;
            /** Format: double */
            readonly unitPrice?: null | number | string;
        };
        readonly OrderPageResponse: {
            readonly items: readonly components["schemas"]["OrderListItemResponse"][];
            readonly nextCursor: null | string;
        };
        readonly OrderResponse: {
            /** Format: uuid */
            readonly id: string;
            readonly sku: string;
            /** Format: int32 */
            readonly quantity: number | string;
            /** Format: date-time */
            readonly placedAt: string;
            /**
             * Format: uuid
             * @description The catalogue product as it was when the order was placed. Null on orders that predate the
             *     catalogue link — those render as the bare sku with no price.
             */
            readonly productId?: null | string;
            readonly productName?: null | string;
            /** Format: double */
            readonly unitPrice?: null | number | string;
        };
        /**
         * @description Where an order is in its life. Persisted by name, like
         *     NotificationKind — the names are a stored contract.
         *
         *     OrderStatus.Placed is first so that it is also the CLR default: rows written before this
         *     column existed materialize as Placed, which is what they were.
         * @enum {unknown}
         */
        readonly OrderStatus: "Placed" | "Shipped" | "Cancelled";
        /** @description What both transition endpoints answer with, so a client can render the new state. */
        readonly OrderStatusResponse: {
            /** Format: uuid */
            readonly orderId: string;
            /** @description Serialized as its name — see `NotificationResponse.Kind`. */
            readonly status: components["schemas"]["OrderStatus"];
            /** Format: date-time */
            readonly changedAt: string;
        };
        /**
         * @description Business-rule validation (non-empty, max length, positive quantity) is owned by
         *     `PlaceOrderValidator` in the validation behavior — not duplicated here as
         *     DataAnnotations. See `src/Api/CLAUDE.md`.
         */
        readonly PlaceOrderRequest: {
            readonly sku: string;
            /** Format: int32 */
            readonly quantity: number | string;
        };
        readonly ProblemDetails: {
            readonly type?: null | string;
            readonly title?: null | string;
            /** Format: int32 */
            readonly status?: null | number | string;
            readonly detail?: null | string;
            readonly instance?: null | string;
        };
        readonly ProductListItemResponse: {
            /** Format: uuid */
            readonly id: string;
            readonly sku: string;
            readonly name: string;
            /** Format: double */
            readonly price: number | string;
            /** Format: date-time */
            readonly createdAt: string;
        };
        readonly ProductPageResponse: {
            readonly items: readonly components["schemas"]["ProductListItemResponse"][];
            readonly nextCursor: null | string;
        };
        readonly ProductResponse: {
            /** Format: uuid */
            readonly id: string;
            readonly sku: string;
            readonly name: string;
            readonly description: null | string;
            /** Format: double */
            readonly price: number | string;
            /** Format: date-time */
            readonly createdAt: string;
            /** Format: date-time */
            readonly updatedAt: string;
        };
        /**
         * @description Business-rule validation (length, charset, password policy) is owned by the validators in
         *     `src/Application/Users`, not duplicated here as DataAnnotations. See `src/Api/CLAUDE.md`.
         */
        readonly RegisterRequest: {
            readonly username: string;
            readonly password: string;
            readonly displayName: string;
        };
        /** @description Who the caller is. Carries no password material, by construction. */
        readonly SessionResponse: {
            /** Format: uuid */
            readonly userId: string;
            readonly username: string;
            readonly displayName: string;
        };
        /** @description The badge count, on its own so a client polling it transfers one number. */
        readonly UnreadCountResponse: {
            /** Format: int32 */
            readonly unreadCount: number | string;
        };
        /**
         * @description No Sku: it is the catalogue's business key and the domain refuses to change it. No Id
         *     either — that comes from the route, so a body that disagreed with the URL could not arise.
         */
        readonly UpdateProductRequest: {
            readonly name: string;
            readonly description?: null | string;
            /** Format: double */
            readonly price: number | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
