// <auto-generated />
using System;
using AiFramework.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiFramework.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AiFrameworkDbContext))]
    [Migration("20261009215839_AddExternalSystemStatus")]
    partial class AddExternalSystemStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiFramework.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceMessageId", "UserId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("IX_Notifications_SourceMessageId_UserId_Kind");

                    b.HasIndex(new[] { "UserId", "CreatedAt", "Id" }, "IX_Notifications_Unread")
                        .IsDescending(false, true, true)
                        .HasFilter("\"ReadAt\" IS NULL");

                    b.HasIndex(new[] { "UserId", "CreatedAt", "Id" }, "IX_Notifications_UserId_CreatedAt_Id_Desc")
                        .IsDescending(false, true, true);

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("AiFramework.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PlacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("ShippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Placed");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Sku", "UserId", "PlacedAt")
                        .HasDatabaseName("IX_Orders_Sku_UserId_PlacedAt");

                    b.HasIndex("Status", "PlacedAt", "Id")
                        .HasDatabaseName("IX_Orders_Status_PlacedAt_Id");

                    b.HasIndex("UserId", "PlacedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_Orders_UserId_PlacedAt_Id_Desc");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("AiFramework.Domain.Orders.OrderExport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Document")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RowCount")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RequestedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_OrderExports_UserId_RequestedAt");

                    b.ToTable("order_exports", (string)null);
                });

            modelBuilder.Entity("AiFramework.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("IX_Products_Sku");

                    b.HasIndex("CreatedAt", "Id")
                        .IsDescending()
                        .HasDatabaseName("IX_Products_CreatedAt_Id_Desc");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("AiFramework.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("FailedSignInAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LockedOutUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Member");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("UsernameNormalized")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("IX_Users_LastSeenAt");

                    b.HasIndex("UsernameNormalized")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_UsernameNormalized");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AiFramework.Infrastructure.Jobs.JobRun", b =>
                {
                    b.Property<Guid>("EnvelopeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("InstanceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Lane")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("EnvelopeId", "Attempt");

                    b.HasIndex("StartedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_JobRuns_StartedAt_Desc");

                    b.HasIndex("Status", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_JobRuns_Status_StartedAt_Desc");

                    b.ToTable("job_runs", (string)null);
                });

            modelBuilder.Entity("AiFramework.Infrastructure.Monitoring.ExternalSystemStatusRow", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("CertificateNotAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool?>("TokenOk")
                        .HasColumnType("boolean");

                    b.HasKey("Name");

                    b.ToTable("external_system_status", (string)null);
                });

            modelBuilder.Entity("AiFramework.Infrastructure.Monitoring.TrafficBucket", b =>
                {
                    b.Property<DateTimeOffset>("BucketStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("InstanceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Bucket0")
                        .HasColumnType("integer");

                    b.Property<int>("Bucket1")
                        .HasColumnType("integer");

                    b.Property<int>("Bucket10")
                        .HasColumnType("integer");

                    b.Property<int>("Bucket2")
                        .HasColumnType("integer");

                    b.Property<int>("Bucket3")
                        .HasColumnType("integer");

                    b.Property<int>("Bucket4")
                        .HasColumnType("integer");

                    b.Property<int>("Bucket5")
                        .HasColumnType("integer");

                    b.Property<int>("Bucket6")
                        .HasColumnType("integer");

                    b.Property<int>("Bucket7")
                        .HasColumnType("integer");

                    b.Property<int>("Bucket8")
                        .HasColumnType("integer");

                    b.Property<int>("Bucket9")
                        .HasColumnType("integer");

                    b.Property<long>("DurationMsTotal")
                        .HasColumnType("bigint");

                    b.Property<int>("Failed")
                        .HasColumnType("integer");

                    b.Property<int>("Faulted")
                        .HasColumnType("integer");

                    b.Property<int>("Succeeded")
                        .HasColumnType("integer");

                    b.HasKey("BucketStart", "Kind", "Name", "InstanceId");

                    b.HasIndex("BucketStart")
                        .IsDescending()
                        .HasDatabaseName("IX_TrafficBuckets_BucketStart_Desc");

                    b.ToTable("traffic_buckets", (string)null);
                });

            modelBuilder.Entity("AiFramework.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("LeasedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_pending");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("AiFramework.Infrastructure.Persistence.OrderAudit", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.HasKey("MessageId");

                    b.ToTable("order_audit", (string)null);
                });

            modelBuilder.Entity("AiFramework.Infrastructure.Security.AdminAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorUsername")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetUsername")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("At")
                        .IsDescending()
                        .HasDatabaseName("IX_AdminActions_At_Desc");

                    b.HasIndex("TargetUserId", "At")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AdminActions_TargetUserId_At_Desc");

                    b.ToTable("admin_actions", (string)null);
                });

            modelBuilder.Entity("AiFramework.Infrastructure.Security.SignInEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UsernameAttempted")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("At")
                        .IsDescending()
                        .HasDatabaseName("IX_SignInEvents_At_Desc");

                    b.HasIndex("Outcome", "At")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_SignInEvents_Outcome_At_Desc");

                    b.ToTable("sign_in_events", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("AiFramework.Domain.Orders.Order", b =>
                {
                    b.OwnsOne("AiFramework.Domain.Orders.OrderedProduct", "Product", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("ProductName");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("ProductId");

                            b1.Property<decimal>("UnitPrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("UnitPrice");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
