<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>ac9fbbb7-d110-4c66-a077-d8399f9a1103</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\AiFramework.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\AiFramework.Infrastructure.csproj" />
  </ItemGroup>

</Project>
